#lang racket

(require "sicp.rkt")
(GETMOD 4 35)

(module+ test
  "===================="
  (amb-test
   '((define (an-integer-between a b)
       (if (<= a b)
           (amb a (an-integer-between (+ 1 a) b))
           (amb)))

     (define (a-pythagorean-triple-between low high)
       (let ((i (an-integer-between low high))
             (hsq (* high high)))
         (let ((j (an-integer-between i high)))
           (let ((ksq (+ (* i i) (* j j))))
             (require (>= hsq ksq))
             (let ((k (sqrt ksq)))
               (require (integer? k))
               (list i j k))))))))
  
  (amb-test '((a-pythagorean-triple-between 1 500)
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              try-again
              ))
  'done)


